### ISSUE TITLE
Tests fail when running in parallel

### ISSUE THREAD

**Issue by DaveGreasley** [gasparnagy/SpecFlow.Autofac#6]
I am trying to run tests in parallel using the NUnit Parallelizable attribute (http://www.specflow.org/documentation/Parallel-Execution/). When my tests run serially they all work fine. Running them in parallel causes the following error on some tests:
```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.ArgumentException : An item with the same key has already been added.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at BoDi.ObjectContainer.InvokeFactoryDelegate(Delegate factoryDelegate, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   at BoDi.ObjectContainer.FactoryRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.Resolve[T](String name)
   at SpecFlow.Autofac.AutofacBindingInstanceResolver.ResolveBindingInstance(Type bindingType, IObjectContainer scenarioContainer)
   at lambda_method(Closure , IContextManager )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType bindingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioStart(ScenarioInfo scenarioInfo)
   at Dyson.Jda.AutomatedTesting.Features.AwardEntrantSignInFeature.ScenarioSetup(ScenarioInfo scenarioInfo)
   at Dyson.Jda.AutomatedTesting.Features.AwardEntrantSignInFeature.AwardEntrantCannotSignInWithInvalidCredentials(String email, String password, String[] exampleTags) in C:\Code\Git\james-dyson-award\JDA\AutomatedTests\Dyson.Jda.AutomatedTesting\Features\AwardEntrantSignIn.feature:line 32
--ArgumentException
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.Resolve[T](String name)
   at SpecFlow.Autofac.AutofacPlugin.<>c__DisplayClass0_0.<Initialize>b__2()
```

BoDi by itself supports running tests in parallel and I have done this successfully on another project. Is it supported by this plugin?

**Comment by gasparnagy** [comment]
Hopefuly "fixed" now. There are tests in the sample project in the `parallel-sample` branch.
